name: Integration tests
on:
  pull_request: {}
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - master
jobs:
  kind_integration_tests:
    name: KinD integration tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Setup KinD
      uses: engineerd/setup-kind@c60b1f94dbba563e5fba9686a1b29ee6b7219958
      with:
        version: v0.11.1
    - name: Docker build
      run: |
        make image
        make tester-image
    - name: Load image into the local KinD cluster
      run: make kind-load
    - name: Run integration tests
      run: SKIP_BUILD_TESTER_IMAGE=1 make integration-test
